# Generated by Django 4.2.6 on 2023-10-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('data_nascimento', models.DateField()),
                ('apelido', models.CharField(max_length=32)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
